name: Run Notion Automation Script Daily

on:
  schedule:
    # This cron job runs every day at 8 AM UTC. Adjust the time as needed.
    - cron: '47 11 * * *'
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # You can change this to the version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # If you have any dependencies listed

    - name: Run the Notion automation script
      run: |
        python notion_script.py  # Run your script
      env:
        NOTION_API_TOKEN: ${{ secrets.NOTION_API_TOKEN }}  # Set your Notion API token as a secret
        DATABASE_ID: ${{ secrets.DATABASE_ID }} 
        SCHEDULE_PAGE_ID: ${{ secrets.SCHEDULE_PAGE_ID }} 